# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_kits', models.IntegerField(blank=True, null=True)),
                ('translation', models.IntegerField(blank=True, null=True)),
                ('mm_prep', models.IntegerField(blank=True, null=True)),
                ('vo', models.IntegerField(blank=True, null=True)),
                ('video_loc', models.IntegerField(blank=True, null=True)),
                ('dtp', models.IntegerField(blank=True, null=True)),
                ('course_build', models.IntegerField(blank=True, null=True)),
                ('course_qa', models.IntegerField(blank=True, null=True)),
                ('course_finalize', models.IntegerField(blank=True, null=True)),
                ('pm', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('tat', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing By Language',
            },
        ),
        migrations.CreateModel(
            name='Scoping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_play_time', models.IntegerField(blank=True, null=True)),
                ('narration_time', models.IntegerField(blank=True, null=True)),
                ('embedded_video_time', models.IntegerField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, null=True)),
                ('transcription', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=8, null=True)),
                ('linked_resources', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_words', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Client')),
            ],
            options={
                'verbose_name_plural': 'Scoping Queries',
            },
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_match', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuzzy_95_99', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuzzy_85_94', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fuzzy_lt_84', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('match_100', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('linguistic_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('qa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('audio_recording_plain', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('audio_recording_timed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dtp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eng', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mm_eng', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Client')),
                ('target_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Language')),
            ],
            options={
                'verbose_name_plural': 'SLA By Client',
            },
        ),
        migrations.AddField(
            model_name='pricing',
            name='scoping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Scoping'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Language'),
        ),
    ]
