# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoping',
            name='ost_elements',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
