# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoping',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
