# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_scoping_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricing Per Language'},
        ),
        migrations.AlterModelOptions(
            name='scoping',
            options={'verbose_name': 'Estimate', 'verbose_name_plural': 'Estimates'},
        ),
    ]
