# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20161209_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='target_language',
            new_name='language',
        ),
    ]
