# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20161209_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sla',
            options={'ordering': ['target_language__name'], 'verbose_name_plural': 'SLA By Client'},
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set([('scoping', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='sla',
            unique_together=set([('client', 'target_language')]),
        ),
    ]
