# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20161210_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
