# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20161210_1114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set([]),
        ),
    ]
