# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20161210_1119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together=set([('scoping', 'language')]),
        ),
    ]
