# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20161210_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='mm_prep',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
