# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20161212_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='mm_prep',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
