# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20161212_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoping',
            name='course_play_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoping',
            name='embedded_video_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoping',
            name='linked_resources',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoping',
            name='narration_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoping',
            name='transcription',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='scoping',
            name='video_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
