# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20161223_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('no_of_files', models.IntegerField(blank=True, default=0, null=True)),
                ('est_total_wordcount', models.IntegerField(blank=True, default=0, null=True)),
                ('actual_total_wordcount', models.IntegerField(blank=True, default=0, null=True)),
                ('editable_pdf_source_available', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=16, null=True)),
                ('path_to_source', models.CharField(blank=True, max_length=128, null=True)),
                ('ts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Scoping')),
            ],
            options={
                'verbose_name_plural': 'PDFs',
            },
        ),
    ]
