# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20170101_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfasset',
            name='total_pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
