# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('selector', models.CharField(default=b'', help_text=b'div:contains("example")', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
